// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vaas/provider/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	types "github.com/allinbits/vaas/x/vaas/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the VAAS provider chain genesis state
type GenesisState struct {
	// strictly positive and set to 1 (DefaultValsetUpdateID) for a new chain
	ValsetUpdateId uint64 `protobuf:"varint,1,opt,name=valset_update_id,json=valsetUpdateId,proto3" json:"valset_update_id,omitempty"`
	// empty for a new chain
	ConsumerStates []ConsumerState `protobuf:"bytes,2,rep,name=consumer_states,json=consumerStates,proto3" json:"consumer_states" yaml:"consumer_states"`
	// empty for a new chain
	ValsetUpdateIdToHeight []ValsetUpdateIdToHeight `protobuf:"bytes,3,rep,name=valset_update_id_to_height,json=valsetUpdateIdToHeight,proto3" json:"valset_update_id_to_height"`
	Params                 Params                   `protobuf:"bytes,4,opt,name=params,proto3" json:"params"`
	// empty for a new chain
	ValidatorConsumerPubkeys []ValidatorConsumerPubKey `protobuf:"bytes,5,rep,name=validator_consumer_pubkeys,json=validatorConsumerPubkeys,proto3" json:"validator_consumer_pubkeys"`
	// empty for a new chain
	ValidatorsByConsumerAddr []ValidatorByConsumerAddr `protobuf:"bytes,6,rep,name=validators_by_consumer_addr,json=validatorsByConsumerAddr,proto3" json:"validators_by_consumer_addr"`
	// empty for a new chain
	ConsumerAddrsToPrune []ConsumerAddrsToPrune `protobuf:"bytes,7,rep,name=consumer_addrs_to_prune,json=consumerAddrsToPrune,proto3" json:"consumer_addrs_to_prune"`
	// empty for a new chain
	ConsumerFeePoolShares []ConsumerFeePoolShare `protobuf:"bytes,8,rep,name=consumer_fee_pool_shares,json=consumerFeePoolShares,proto3" json:"consumer_fee_pool_shares"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9071b84cde652f9, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetValsetUpdateId() uint64 {
	if m != nil {
		return m.ValsetUpdateId
	}
	return 0
}

func (m *GenesisState) GetConsumerStates() []ConsumerState {
	if m != nil {
		return m.ConsumerStates
	}
	return nil
}

func (m *GenesisState) GetValsetUpdateIdToHeight() []ValsetUpdateIdToHeight {
	if m != nil {
		return m.ValsetUpdateIdToHeight
	}
	return nil
}

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetValidatorConsumerPubkeys() []ValidatorConsumerPubKey {
	if m != nil {
		return m.ValidatorConsumerPubkeys
	}
	return nil
}

func (m *GenesisState) GetValidatorsByConsumerAddr() []ValidatorByConsumerAddr {
	if m != nil {
		return m.ValidatorsByConsumerAddr
	}
	return nil
}

func (m *GenesisState) GetConsumerAddrsToPrune() []ConsumerAddrsToPrune {
	if m != nil {
		return m.ConsumerAddrsToPrune
	}
	return nil
}

func (m *GenesisState) GetConsumerFeePoolShares() []ConsumerFeePoolShare {
	if m != nil {
		return m.ConsumerFeePoolShares
	}
	return nil
}

// The provider VAAS module's knowledge of consumer state.
//
// Note this type is only used internally to the provider VAAS module.
type ConsumerState struct {
	// ConsumerID is the internal numeric consumer id.
	ConsumerId uint64 `protobuf:"varint,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	// ChainID is the external chain identifier of the consumer chain (e.g.
	// "atomone-1"), as supplied by the consumer owner at registration.
	ChainId string `protobuf:"bytes,2,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	// ClientID defines the IBC client ID for the consumer chain.
	ClientId string `protobuf:"bytes,3,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// InitialHeight defines the initial block height for the consumer chain
	InitialHeight uint64 `protobuf:"varint,4,opt,name=initial_height,json=initialHeight,proto3" json:"initial_height,omitempty"`
	// ConsumerGenesis defines the initial consumer chain genesis states
	ConsumerGenesis types.ConsumerGenesisState `protobuf:"bytes,5,opt,name=consumer_genesis,json=consumerGenesis,proto3" json:"consumer_genesis"`
	// PendingValsetChanges defines the pending validator set changes for the
	// consumer chain
	PendingValsetChanges []types.ValidatorSetChangePacketData `protobuf:"bytes,6,rep,name=pending_valset_changes,json=pendingValsetChanges,proto3" json:"pending_valset_changes"`
	SlashDowntimeAck     []string                             `protobuf:"bytes,7,rep,name=slash_downtime_ack,json=slashDowntimeAck,proto3" json:"slash_downtime_ack,omitempty"`
	// the phase of the consumer chain
	Phase ConsumerPhase `protobuf:"varint,8,opt,name=phase,proto3,enum=vaas.provider.v1.ConsumerPhase" json:"phase,omitempty"`
	// OwnerAddress is the bech32 address that authorises owner-only operations
	// (UpdateConsumer, RemoveConsumer, key assignment, etc.) on the consumer.
	// Always non-empty for any existing consumer record; set at REGISTERED.
	OwnerAddress string `protobuf:"bytes,9,opt,name=owner_address,json=ownerAddress,proto3" json:"owner_address,omitempty"`
	// Metadata is the owner-supplied descriptor (name/description/repo).
	// Preserved through DELETED so block explorers can show information
	// about removed chains without an archive node.
	Metadata *ConsumerMetadata `protobuf:"bytes,10,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// InitParams are the owner-supplied launch parameters: spawn time,
	// initial height, genesis hash, binary hash, etc. Preserved through
	// DELETED for the same explorer reason. Carries the spawn_time used
	// to re-derive the keeper's spawn-time queue, and the initial_height
	// used to re-derive equivocation_evidence_min_height, at InitGenesis.
	InitParams *ConsumerInitializationParameters `protobuf:"bytes,11,opt,name=init_params,json=initParams,proto3" json:"init_params,omitempty"`
	// RemovalTime is the wall-clock time at which a STOPPED consumer is
	// scheduled to transition to DELETED. Set only when phase == STOPPED;
	// absent otherwise. Used to re-derive the keeper's removal-time queue.
	RemovalTime *time.Time `protobuf:"bytes,12,opt,name=removal_time,json=removalTime,proto3,stdtime" json:"removal_time,omitempty"`
}

func (m *ConsumerState) Reset()         { *m = ConsumerState{} }
func (m *ConsumerState) String() string { return proto.CompactTextString(m) }
func (*ConsumerState) ProtoMessage()    {}
func (*ConsumerState) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9071b84cde652f9, []int{1}
}
func (m *ConsumerState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumerState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumerState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumerState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerState.Merge(m, src)
}
func (m *ConsumerState) XXX_Size() int {
	return m.Size()
}
func (m *ConsumerState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerState proto.InternalMessageInfo

func (m *ConsumerState) GetConsumerId() uint64 {
	if m != nil {
		return m.ConsumerId
	}
	return 0
}

func (m *ConsumerState) GetChainId() string {
	if m != nil {
		return m.ChainId
	}
	return ""
}

func (m *ConsumerState) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *ConsumerState) GetInitialHeight() uint64 {
	if m != nil {
		return m.InitialHeight
	}
	return 0
}

func (m *ConsumerState) GetConsumerGenesis() types.ConsumerGenesisState {
	if m != nil {
		return m.ConsumerGenesis
	}
	return types.ConsumerGenesisState{}
}

func (m *ConsumerState) GetPendingValsetChanges() []types.ValidatorSetChangePacketData {
	if m != nil {
		return m.PendingValsetChanges
	}
	return nil
}

func (m *ConsumerState) GetSlashDowntimeAck() []string {
	if m != nil {
		return m.SlashDowntimeAck
	}
	return nil
}

func (m *ConsumerState) GetPhase() ConsumerPhase {
	if m != nil {
		return m.Phase
	}
	return CONSUMER_PHASE_UNSPECIFIED
}

func (m *ConsumerState) GetOwnerAddress() string {
	if m != nil {
		return m.OwnerAddress
	}
	return ""
}

func (m *ConsumerState) GetMetadata() *ConsumerMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *ConsumerState) GetInitParams() *ConsumerInitializationParameters {
	if m != nil {
		return m.InitParams
	}
	return nil
}

func (m *ConsumerState) GetRemovalTime() *time.Time {
	if m != nil {
		return m.RemovalTime
	}
	return nil
}

// ValsetUpdateIdToHeight defines the genesis information for the mapping
// of each valset update id to a block height
type ValsetUpdateIdToHeight struct {
	ValsetUpdateId uint64 `protobuf:"varint,1,opt,name=valset_update_id,json=valsetUpdateId,proto3" json:"valset_update_id,omitempty"`
	Height         uint64 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *ValsetUpdateIdToHeight) Reset()         { *m = ValsetUpdateIdToHeight{} }
func (m *ValsetUpdateIdToHeight) String() string { return proto.CompactTextString(m) }
func (*ValsetUpdateIdToHeight) ProtoMessage()    {}
func (*ValsetUpdateIdToHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9071b84cde652f9, []int{2}
}
func (m *ValsetUpdateIdToHeight) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValsetUpdateIdToHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValsetUpdateIdToHeight.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValsetUpdateIdToHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValsetUpdateIdToHeight.Merge(m, src)
}
func (m *ValsetUpdateIdToHeight) XXX_Size() int {
	return m.Size()
}
func (m *ValsetUpdateIdToHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_ValsetUpdateIdToHeight.DiscardUnknown(m)
}

var xxx_messageInfo_ValsetUpdateIdToHeight proto.InternalMessageInfo

func (m *ValsetUpdateIdToHeight) GetValsetUpdateId() uint64 {
	if m != nil {
		return m.ValsetUpdateId
	}
	return 0
}

func (m *ValsetUpdateIdToHeight) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// ConsumerFeePoolShare is a single depositor's share holding in a consumer
// fee pool, scoped to one denom. The triple (consumer_id, depositor, denom)
// is unique.
type ConsumerFeePoolShare struct {
	ConsumerId string                `protobuf:"bytes,1,opt,name=consumer_id,json=consumerId,proto3" json:"consumer_id,omitempty"`
	Depositor  string                `protobuf:"bytes,2,opt,name=depositor,proto3" json:"depositor,omitempty"`
	Denom      string                `protobuf:"bytes,3,opt,name=denom,proto3" json:"denom,omitempty"`
	Shares     cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=shares,proto3,customtype=cosmossdk.io/math.Int" json:"shares"`
}

func (m *ConsumerFeePoolShare) Reset()         { *m = ConsumerFeePoolShare{} }
func (m *ConsumerFeePoolShare) String() string { return proto.CompactTextString(m) }
func (*ConsumerFeePoolShare) ProtoMessage()    {}
func (*ConsumerFeePoolShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9071b84cde652f9, []int{3}
}
func (m *ConsumerFeePoolShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumerFeePoolShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumerFeePoolShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumerFeePoolShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerFeePoolShare.Merge(m, src)
}
func (m *ConsumerFeePoolShare) XXX_Size() int {
	return m.Size()
}
func (m *ConsumerFeePoolShare) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerFeePoolShare.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerFeePoolShare proto.InternalMessageInfo

func (m *ConsumerFeePoolShare) GetConsumerId() string {
	if m != nil {
		return m.ConsumerId
	}
	return ""
}

func (m *ConsumerFeePoolShare) GetDepositor() string {
	if m != nil {
		return m.Depositor
	}
	return ""
}

func (m *ConsumerFeePoolShare) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "vaas.provider.v1.GenesisState")
	proto.RegisterType((*ConsumerState)(nil), "vaas.provider.v1.ConsumerState")
	proto.RegisterType((*ValsetUpdateIdToHeight)(nil), "vaas.provider.v1.ValsetUpdateIdToHeight")
	proto.RegisterType((*ConsumerFeePoolShare)(nil), "vaas.provider.v1.ConsumerFeePoolShare")
}

func init() { proto.RegisterFile("vaas/provider/v1/genesis.proto", fileDescriptor_c9071b84cde652f9) }

var fileDescriptor_c9071b84cde652f9 = []byte{
	// 938 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x17, 0x35, 0x6d, 0x49, 0x91, 0x46, 0xb6, 0x3f, 0x63, 0xa0, 0xe8, 0x63, 0x1c, 0x44, 0x12, 0x54,
	0xa4, 0x50, 0xd1, 0x86, 0x84, 0x5d, 0x34, 0x8b, 0x2e, 0x0a, 0x58, 0x0e, 0xda, 0x0a, 0x45, 0x0b,
	0x81, 0x72, 0xbb, 0xc8, 0x86, 0x18, 0x71, 0x26, 0xe4, 0x54, 0x24, 0x87, 0xe0, 0x8c, 0xe8, 0xaa,
	0x4f, 0x91, 0xa7, 0xe8, 0x13, 0xe4, 0x21, 0x82, 0xae, 0x82, 0xac, 0x8a, 0x2e, 0xdc, 0xc2, 0x7e,
	0x82, 0xf6, 0x09, 0x8a, 0xf9, 0x21, 0x63, 0xd9, 0x72, 0x83, 0xee, 0x34, 0xf7, 0x9c, 0x39, 0xe7,
	0x72, 0xee, 0x8f, 0x40, 0xaf, 0x40, 0x88, 0xbb, 0x59, 0xce, 0x0a, 0x8a, 0x49, 0xee, 0x16, 0x47,
	0x6e, 0x48, 0x52, 0xc2, 0x29, 0x77, 0xb2, 0x9c, 0x09, 0x06, 0x0f, 0x24, 0xee, 0x94, 0xb8, 0x53,
	0x1c, 0x1d, 0x76, 0x42, 0x16, 0x32, 0x05, 0xba, 0xf2, 0x97, 0xe6, 0x1d, 0xf6, 0x43, 0xc6, 0xc2,
	0x98, 0xb8, 0xea, 0x34, 0x5f, 0xbe, 0x70, 0x05, 0x4d, 0x08, 0x17, 0x28, 0xc9, 0x0c, 0xe1, 0x41,
	0xc0, 0x78, 0xc2, 0xb8, 0xaf, 0x6f, 0xea, 0x83, 0x81, 0x1e, 0xa9, 0x1c, 0x8a, 0x23, 0x97, 0x47,
	0x28, 0x27, 0xd8, 0x0f, 0x58, 0xca, 0x97, 0x09, 0xc9, 0x0d, 0x0c, 0x4b, 0xf8, 0x9c, 0xe6, 0xa4,
	0xb4, 0xbb, 0x95, 0x76, 0x95, 0xa2, 0x22, 0x0c, 0xff, 0xaa, 0x83, 0xdd, 0xaf, 0xf4, 0x97, 0xcc,
	0x04, 0x12, 0x04, 0x8e, 0xc0, 0x41, 0x81, 0x62, 0x4e, 0x84, 0xbf, 0xcc, 0x30, 0x12, 0xc4, 0xa7,
	0xd8, 0xb6, 0x06, 0xd6, 0xa8, 0xe6, 0xed, 0xeb, 0xf8, 0xf7, 0x2a, 0x3c, 0xc1, 0x30, 0x02, 0xff,
	0x2b, 0x33, 0xf0, 0xb9, 0xbc, 0xcb, 0xed, 0xed, 0xc1, 0xce, 0xa8, 0x7d, 0xdc, 0x77, 0x6e, 0x3e,
	0x86, 0x73, 0x6a, 0x88, 0xca, 0x63, 0xdc, 0x7b, 0x7d, 0xd1, 0xdf, 0xfa, 0xfb, 0xa2, 0xdf, 0x5d,
	0xa1, 0x24, 0xfe, 0x7c, 0x78, 0x43, 0x65, 0xe8, 0xed, 0x07, 0xd7, 0xe9, 0x1c, 0xfe, 0x08, 0x0e,
	0x6f, 0xe6, 0xe4, 0x0b, 0xe6, 0x47, 0x84, 0x86, 0x91, 0xb0, 0x77, 0x94, 0xe9, 0xe8, 0xb6, 0xe9,
	0x0f, 0x6b, 0xf9, 0x9e, 0xb1, 0xaf, 0x15, 0x7f, 0x5c, 0x93, 0xee, 0x5e, 0xb7, 0xd8, 0x88, 0xc2,
	0xa7, 0xa0, 0x91, 0xa1, 0x1c, 0x25, 0xdc, 0xae, 0x0d, 0xac, 0x51, 0xfb, 0xd8, 0xbe, 0xad, 0x3b,
	0x55, 0xb8, 0xd1, 0x31, 0x6c, 0x98, 0xa8, 0x1c, 0x29, 0x46, 0x82, 0xe5, 0x55, 0x65, 0xfc, 0x6c,
	0x39, 0x5f, 0x90, 0x15, 0xb7, 0xeb, 0x2a, 0xc7, 0x8f, 0x36, 0xe6, 0xa8, 0xef, 0x94, 0x2f, 0x34,
	0x5d, 0xce, 0xbf, 0x21, 0x2b, 0x23, 0x6e, 0x17, 0x1b, 0x60, 0x29, 0x08, 0x53, 0xf0, 0xb0, 0xc2,
	0xb8, 0x3f, 0x5f, 0xbd, 0xb3, 0x44, 0x18, 0xe7, 0x76, 0xe3, 0xbd, 0x7e, 0xe3, 0x55, 0x29, 0x79,
	0x82, 0x71, 0x7e, 0xcb, 0x8f, 0xaf, 0xe3, 0x30, 0x00, 0xff, 0x5f, 0x73, 0xe0, 0xb2, 0x00, 0x59,
	0xbe, 0x4c, 0x89, 0x7d, 0x4f, 0x79, 0x7d, 0x78, 0x77, 0xd1, 0xa5, 0x00, 0x3f, 0x63, 0x53, 0xc9,
	0x36, 0x46, 0x9d, 0x60, 0x03, 0x06, 0x09, 0xb0, 0x2b, 0x93, 0x17, 0x84, 0xf8, 0x19, 0x63, 0xb1,
	0xaf, 0x9a, 0x9d, 0xdb, 0xcd, 0xf7, 0xb9, 0x7c, 0x49, 0xc8, 0x94, 0xb1, 0x78, 0x26, 0xe9, 0xc6,
	0xe5, 0x7e, 0xb0, 0x01, 0xe3, 0xc3, 0x5f, 0xea, 0x60, 0x6f, 0xad, 0x21, 0x61, 0x1f, 0xb4, 0x2b,
	0xe3, 0xaa, 0xdf, 0x41, 0x19, 0x9a, 0x60, 0xf8, 0x00, 0x34, 0x83, 0x08, 0xd1, 0x54, 0xa2, 0xdb,
	0x03, 0x6b, 0xd4, 0xf2, 0xee, 0xa9, 0xf3, 0x04, 0xc3, 0x87, 0xa0, 0x15, 0xc4, 0x94, 0xa4, 0x42,
	0x62, 0x3b, 0x0a, 0x6b, 0xea, 0xc0, 0x04, 0xc3, 0xc7, 0x60, 0x9f, 0xa6, 0x54, 0x50, 0x14, 0x97,
	0xdd, 0x5a, 0x53, 0xda, 0x7b, 0x26, 0x6a, 0x9a, 0xee, 0x3b, 0x70, 0x50, 0xf9, 0x9b, 0xbd, 0x62,
	0xd7, 0x55, 0xfb, 0x3d, 0xd2, 0x1f, 0x7c, 0xed, 0x3b, 0xaf, 0x4f, 0xab, 0xf9, 0xce, 0x6a, 0x0e,
	0x0d, 0x06, 0x11, 0xe8, 0x66, 0x24, 0xc5, 0x34, 0x0d, 0x7d, 0x33, 0x38, 0x41, 0x84, 0xd2, 0x90,
	0x70, 0xd3, 0x18, 0x8f, 0x2b, 0xd5, 0xaa, 0x1f, 0x66, 0x44, 0x9c, 0x2a, 0xce, 0x14, 0x05, 0x0b,
	0x22, 0x9e, 0x21, 0x81, 0xca, 0x5a, 0x19, 0x29, 0x3d, 0x4e, 0x9a, 0xc4, 0xe1, 0x27, 0x00, 0xf2,
	0x18, 0xf1, 0xc8, 0xc7, 0xec, 0x3c, 0x95, 0x4b, 0xcc, 0x47, 0xc1, 0x42, 0xf5, 0x42, 0xcb, 0x3b,
	0x50, 0xc8, 0x33, 0x03, 0x9c, 0x04, 0x0b, 0xf8, 0x19, 0xa8, 0x67, 0x11, 0xe2, 0xc4, 0x6e, 0x0e,
	0xac, 0xd1, 0xfe, 0xbf, 0x6d, 0x88, 0xa9, 0xa4, 0x79, 0x9a, 0x0d, 0x3f, 0x00, 0x7b, 0xec, 0x3c,
	0x35, 0x2d, 0x47, 0x38, 0xb7, 0x5b, 0xea, 0x7d, 0x77, 0x55, 0xf0, 0x44, 0xc7, 0xe0, 0x17, 0xa0,
	0x99, 0x10, 0x81, 0x30, 0x12, 0xc8, 0x06, 0xea, 0xd1, 0x86, 0x77, 0xcb, 0x7f, 0x6b, 0x98, 0x5e,
	0x75, 0x07, 0xce, 0x40, 0x5b, 0x56, 0xc3, 0x37, 0x63, 0xdf, 0x56, 0x12, 0xc7, 0x77, 0x4b, 0x4c,
	0x74, 0xe9, 0xe8, 0xcf, 0x48, 0x50, 0x96, 0xaa, 0x65, 0x40, 0x04, 0xc9, 0xb9, 0x07, 0xa4, 0x8c,
	0x5e, 0x0e, 0xf0, 0x14, 0xec, 0xe6, 0x24, 0x61, 0x05, 0x8a, 0x7d, 0xf9, 0x06, 0xf6, 0xae, 0x52,
	0x3d, 0x74, 0xf4, 0xfa, 0x77, 0xca, 0xf5, 0xef, 0x9c, 0x95, 0xeb, 0x7f, 0x5c, 0x7b, 0xf9, 0x47,
	0xdf, 0xf2, 0xda, 0xe6, 0x96, 0x8c, 0x0f, 0x9f, 0x83, 0xee, 0xe6, 0x1d, 0xf6, 0x1f, 0xb6, 0x74,
	0x17, 0x34, 0x4c, 0xe7, 0x6d, 0x2b, 0xdc, 0x9c, 0x86, 0xbf, 0x5a, 0xa0, 0xb3, 0x69, 0x74, 0x36,
	0xcd, 0x42, 0x6b, 0x6d, 0x16, 0x9e, 0x82, 0x16, 0x26, 0x19, 0xe3, 0x54, 0xb0, 0x5c, 0x0f, 0xc3,
	0xd8, 0x7e, 0xfb, 0xea, 0x49, 0xc7, 0xfc, 0x57, 0x99, 0xb2, 0xcc, 0x44, 0x4e, 0xd3, 0xd0, 0x7b,
	0x47, 0x85, 0x1d, 0x50, 0xc7, 0x24, 0x65, 0x89, 0x19, 0x12, 0x7d, 0x80, 0xa7, 0xa0, 0x61, 0x26,
	0xbc, 0xa6, 0xa4, 0x3e, 0x96, 0x3d, 0xf7, 0xfb, 0x45, 0xff, 0xbe, 0x96, 0xe3, 0x78, 0xe1, 0x50,
	0xe6, 0x26, 0x48, 0x44, 0xce, 0x24, 0x15, 0x6f, 0x5f, 0x3d, 0x01, 0xc6, 0x67, 0x92, 0x0a, 0xcf,
	0x5c, 0x1d, 0x4f, 0x5e, 0x5f, 0xf6, 0xac, 0x37, 0x97, 0x3d, 0xeb, 0xcf, 0xcb, 0x9e, 0xf5, 0xf2,
	0xaa, 0xb7, 0xf5, 0xe6, 0xaa, 0xb7, 0xf5, 0xdb, 0x55, 0x6f, 0xeb, 0xb9, 0x1b, 0x52, 0x11, 0x2d,
	0xe7, 0x4e, 0xc0, 0x12, 0x17, 0xc5, 0x31, 0x4d, 0xe7, 0x54, 0x70, 0x57, 0xfd, 0x2b, 0xfe, 0xe4,
	0xae, 0xff, 0x39, 0x8a, 0x55, 0x46, 0xf8, 0xbc, 0xa1, 0x4a, 0xf3, 0xe9, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xc6, 0xd1, 0x61, 0x40, 0xf1, 0x07, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConsumerFeePoolShares) > 0 {
		for iNdEx := len(m.ConsumerFeePoolShares) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ConsumerFeePoolShares[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.ConsumerAddrsToPrune) > 0 {
		for iNdEx := len(m.ConsumerAddrsToPrune) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ConsumerAddrsToPrune[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.ValidatorsByConsumerAddr) > 0 {
		for iNdEx := len(m.ValidatorsByConsumerAddr) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorsByConsumerAddr[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ValidatorConsumerPubkeys) > 0 {
		for iNdEx := len(m.ValidatorConsumerPubkeys) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorConsumerPubkeys[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.ValsetUpdateIdToHeight) > 0 {
		for iNdEx := len(m.ValsetUpdateIdToHeight) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValsetUpdateIdToHeight[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.ConsumerStates) > 0 {
		for iNdEx := len(m.ConsumerStates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ConsumerStates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.ValsetUpdateId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ValsetUpdateId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ConsumerState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumerState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RemovalTime != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.RemovalTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RemovalTime):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintGenesis(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x62
	}
	if m.InitParams != nil {
		{
			size, err := m.InitParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x5a
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x52
	}
	if len(m.OwnerAddress) > 0 {
		i -= len(m.OwnerAddress)
		copy(dAtA[i:], m.OwnerAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.OwnerAddress)))
		i--
		dAtA[i] = 0x4a
	}
	if m.Phase != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Phase))
		i--
		dAtA[i] = 0x40
	}
	if len(m.SlashDowntimeAck) > 0 {
		for iNdEx := len(m.SlashDowntimeAck) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.SlashDowntimeAck[iNdEx])
			copy(dAtA[i:], m.SlashDowntimeAck[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.SlashDowntimeAck[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.PendingValsetChanges) > 0 {
		for iNdEx := len(m.PendingValsetChanges) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingValsetChanges[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	{
		size, err := m.ConsumerGenesis.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.InitialHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.InitialHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0x12
	}
	if m.ConsumerId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ConsumerId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ValsetUpdateIdToHeight) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValsetUpdateIdToHeight) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValsetUpdateIdToHeight) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if m.ValsetUpdateId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.ValsetUpdateId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ConsumerFeePoolShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumerFeePoolShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerFeePoolShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Shares.Size()
		i -= size
		if _, err := m.Shares.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Depositor) > 0 {
		i -= len(m.Depositor)
		copy(dAtA[i:], m.Depositor)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Depositor)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ConsumerId) > 0 {
		i -= len(m.ConsumerId)
		copy(dAtA[i:], m.ConsumerId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ConsumerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValsetUpdateId != 0 {
		n += 1 + sovGenesis(uint64(m.ValsetUpdateId))
	}
	if len(m.ConsumerStates) > 0 {
		for _, e := range m.ConsumerStates {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValsetUpdateIdToHeight) > 0 {
		for _, e := range m.ValsetUpdateIdToHeight {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.ValidatorConsumerPubkeys) > 0 {
		for _, e := range m.ValidatorConsumerPubkeys {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorsByConsumerAddr) > 0 {
		for _, e := range m.ValidatorsByConsumerAddr {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ConsumerAddrsToPrune) > 0 {
		for _, e := range m.ConsumerAddrsToPrune {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ConsumerFeePoolShares) > 0 {
		for _, e := range m.ConsumerFeePoolShares {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *ConsumerState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ConsumerId != 0 {
		n += 1 + sovGenesis(uint64(m.ConsumerId))
	}
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.InitialHeight != 0 {
		n += 1 + sovGenesis(uint64(m.InitialHeight))
	}
	l = m.ConsumerGenesis.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.PendingValsetChanges) > 0 {
		for _, e := range m.PendingValsetChanges {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SlashDowntimeAck) > 0 {
		for _, s := range m.SlashDowntimeAck {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Phase != 0 {
		n += 1 + sovGenesis(uint64(m.Phase))
	}
	l = len(m.OwnerAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.InitParams != nil {
		l = m.InitParams.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.RemovalTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.RemovalTime)
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *ValsetUpdateIdToHeight) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ValsetUpdateId != 0 {
		n += 1 + sovGenesis(uint64(m.ValsetUpdateId))
	}
	if m.Height != 0 {
		n += 1 + sovGenesis(uint64(m.Height))
	}
	return n
}

func (m *ConsumerFeePoolShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsumerId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Depositor)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Shares.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValsetUpdateId", wireType)
			}
			m.ValsetUpdateId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValsetUpdateId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerStates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerStates = append(m.ConsumerStates, ConsumerState{})
			if err := m.ConsumerStates[len(m.ConsumerStates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValsetUpdateIdToHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValsetUpdateIdToHeight = append(m.ValsetUpdateIdToHeight, ValsetUpdateIdToHeight{})
			if err := m.ValsetUpdateIdToHeight[len(m.ValsetUpdateIdToHeight)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorConsumerPubkeys", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorConsumerPubkeys = append(m.ValidatorConsumerPubkeys, ValidatorConsumerPubKey{})
			if err := m.ValidatorConsumerPubkeys[len(m.ValidatorConsumerPubkeys)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorsByConsumerAddr", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorsByConsumerAddr = append(m.ValidatorsByConsumerAddr, ValidatorByConsumerAddr{})
			if err := m.ValidatorsByConsumerAddr[len(m.ValidatorsByConsumerAddr)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerAddrsToPrune", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerAddrsToPrune = append(m.ConsumerAddrsToPrune, ConsumerAddrsToPrune{})
			if err := m.ConsumerAddrsToPrune[len(m.ConsumerAddrsToPrune)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerFeePoolShares", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerFeePoolShares = append(m.ConsumerFeePoolShares, ConsumerFeePoolShare{})
			if err := m.ConsumerFeePoolShares[len(m.ConsumerFeePoolShares)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsumerState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumerState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumerState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerId", wireType)
			}
			m.ConsumerId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ConsumerId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialHeight", wireType)
			}
			m.InitialHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InitialHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerGenesis", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ConsumerGenesis.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingValsetChanges", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingValsetChanges = append(m.PendingValsetChanges, types.ValidatorSetChangePacketData{})
			if err := m.PendingValsetChanges[len(m.PendingValsetChanges)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SlashDowntimeAck", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SlashDowntimeAck = append(m.SlashDowntimeAck, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phase", wireType)
			}
			m.Phase = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Phase |= ConsumerPhase(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OwnerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OwnerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &ConsumerMetadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.InitParams == nil {
				m.InitParams = &ConsumerInitializationParameters{}
			}
			if err := m.InitParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RemovalTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RemovalTime == nil {
				m.RemovalTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.RemovalTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValsetUpdateIdToHeight) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValsetUpdateIdToHeight: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValsetUpdateIdToHeight: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValsetUpdateId", wireType)
			}
			m.ValsetUpdateId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValsetUpdateId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsumerFeePoolShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumerFeePoolShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumerFeePoolShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsumerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Depositor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Depositor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Shares", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Shares.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
