// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vaas/consumer/v1/genesis.proto

package types

import (
	fmt "fmt"
	types "github.com/allinbits/vaas/x/vaas/types"
	_ "github.com/cometbft/cometbft/abci/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_ "github.com/cosmos/ibc-go/v10/modules/light-clients/07-tendermint"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the VAAS consumer genesis state
//
// Note: this type is only used on consumer side and references shared types
// with provider
type GenesisState struct {
	// ConsumerParams is a shared type with provider module
	Params types.ConsumerParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// Client ID of the provider. This is the primary identifier for the provider.
	ProviderClientId string `protobuf:"bytes,2,opt,name=provider_client_id,json=providerClientId,proto3" json:"provider_client_id,omitempty"`
	// true for new chain, false for chain restart.
	NewChain bool `protobuf:"varint,3,opt,name=new_chain,json=newChain,proto3" json:"new_chain,omitempty"`
	// Flag indicating whether the consumer VAAS module starts in pre-VAAS state
	PreVAAS  bool               `protobuf:"varint,4,opt,name=preVAAS,proto3" json:"preVAAS,omitempty"`
	Provider types.ProviderInfo `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider"`
	// LastVSCRecvTime is the block time of the last VSC packet the consumer
	// received; it drives IsVSCStale (safe mode). Round-tripped on restart so a
	// state-export upgrade preserves the staleness clock. Absent for a new chain
	// that has not received a VSC yet.
	LastVscRecvTime *time.Time `protobuf:"bytes,6,opt,name=last_vsc_recv_time,json=lastVscRecvTime,proto3,stdtime" json:"last_vsc_recv_time,omitempty"`
	// Missed-block bitmaps for validators currently tracked within the open
	// downtime window. Empty for a new chain or right after a window closes.
	MissedBlockBitmaps []MissedBlockBitmapEntry `protobuf:"bytes,7,rep,name=missed_block_bitmaps,json=missedBlockBitmaps,proto3" json:"missed_block_bitmaps"`
	// First height at which each currently-tracked validator was observed
	// within the open downtime window. Empty for a new chain or right after a
	// window closes.
	FirstTrackedHeights []FirstTrackedHeightEntry `protobuf:"bytes,8,rep,name=first_tracked_heights,json=firstTrackedHeights,proto3" json:"first_tracked_heights"`
	// Downtime params staged to take effect at the next window boundary.
	// Absent means nothing is staged.
	StagedDowntimeParams *types.DowntimeParams `protobuf:"bytes,9,opt,name=staged_downtime_params,json=stagedDowntimeParams,proto3" json:"staged_downtime_params,omitempty"`
	// ProviderChainId is the chain id the consumer has pinned as belonging to
	// the provider (see ProviderChainId in x/vaas/consumer/keeper/keeper.go).
	// Round-tripped on restart so a state-export restart preserves the pin
	// instead of leaving a window with no pin until the next VSC packet
	// re-establishes it. Empty for a new chain that has not launched yet.
	ProviderChainId string `protobuf:"bytes,10,opt,name=provider_chain_id,json=providerChainId,proto3" json:"provider_chain_id,omitempty"`
	// Downtime evidence packets queued for send to the provider. Round-tripped
	// on restart because closing a window clears the source bitmaps, leaving
	// the queue as the only remaining copy of the evidence. Empty for a new
	// chain or when nothing is queued.
	PendingEvidencePackets []PendingEvidencePacketEntry `protobuf:"bytes,11,rep,name=pending_evidence_packets,json=pendingEvidencePackets,proto3" json:"pending_evidence_packets"`
	// HighestValsetUpdateId is the highest VSC id the consumer has applied: the
	// out-of-order dedup watermark (see OnRecvVSCPacketV2 in
	// x/vaas/consumer/keeper/relay.go), which skips any VSC packet whose id is
	// not greater than it. Round-tripped on restart so a state-export restart
	// keeps rejecting stale diffs still held in IBC state, instead of resetting
	// the watermark and re-applying an older set over a newer one. Absent (0)
	// for a new chain or a consumer that has not yet applied a VSC.
	HighestValsetUpdateId uint64 `protobuf:"varint,12,opt,name=highest_valset_update_id,json=highestValsetUpdateId,proto3" json:"highest_valset_update_id,omitempty"`
	// ConsumerInDebt is the debt flag the provider last stamped on an accepted
	// VSC packet: one of the two arms of the consumer's tx-admission gate (see
	// IsConsumerInDebt and NewMsgFilterDecorator), the other being
	// last_vsc_recv_time. Round-tripped on restart so a debt-gated consumer
	// comes back gated instead of admitting ordinary transactions until the
	// next VSC packet re-asserts the flag. False for a new chain or a consumer
	// that has never been in debt.
	ConsumerInDebt bool `protobuf:"varint,13,opt,name=consumer_in_debt,json=consumerInDebt,proto3" json:"consumer_in_debt,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc650057d919c311, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() types.ConsumerParams {
	if m != nil {
		return m.Params
	}
	return types.ConsumerParams{}
}

func (m *GenesisState) GetProviderClientId() string {
	if m != nil {
		return m.ProviderClientId
	}
	return ""
}

func (m *GenesisState) GetNewChain() bool {
	if m != nil {
		return m.NewChain
	}
	return false
}

func (m *GenesisState) GetPreVAAS() bool {
	if m != nil {
		return m.PreVAAS
	}
	return false
}

func (m *GenesisState) GetProvider() types.ProviderInfo {
	if m != nil {
		return m.Provider
	}
	return types.ProviderInfo{}
}

func (m *GenesisState) GetLastVscRecvTime() *time.Time {
	if m != nil {
		return m.LastVscRecvTime
	}
	return nil
}

func (m *GenesisState) GetMissedBlockBitmaps() []MissedBlockBitmapEntry {
	if m != nil {
		return m.MissedBlockBitmaps
	}
	return nil
}

func (m *GenesisState) GetFirstTrackedHeights() []FirstTrackedHeightEntry {
	if m != nil {
		return m.FirstTrackedHeights
	}
	return nil
}

func (m *GenesisState) GetStagedDowntimeParams() *types.DowntimeParams {
	if m != nil {
		return m.StagedDowntimeParams
	}
	return nil
}

func (m *GenesisState) GetProviderChainId() string {
	if m != nil {
		return m.ProviderChainId
	}
	return ""
}

func (m *GenesisState) GetPendingEvidencePackets() []PendingEvidencePacketEntry {
	if m != nil {
		return m.PendingEvidencePackets
	}
	return nil
}

func (m *GenesisState) GetHighestValsetUpdateId() uint64 {
	if m != nil {
		return m.HighestValsetUpdateId
	}
	return 0
}

func (m *GenesisState) GetConsumerInDebt() bool {
	if m != nil {
		return m.ConsumerInDebt
	}
	return false
}

// MissedBlockBitmapEntry is a single validator's missed-block bitmap for the
// downtime window currently in progress.
type MissedBlockBitmapEntry struct {
	Addr   []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Bitmap []byte `protobuf:"bytes,2,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
}

func (m *MissedBlockBitmapEntry) Reset()         { *m = MissedBlockBitmapEntry{} }
func (m *MissedBlockBitmapEntry) String() string { return proto.CompactTextString(m) }
func (*MissedBlockBitmapEntry) ProtoMessage()    {}
func (*MissedBlockBitmapEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc650057d919c311, []int{1}
}
func (m *MissedBlockBitmapEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MissedBlockBitmapEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MissedBlockBitmapEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MissedBlockBitmapEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissedBlockBitmapEntry.Merge(m, src)
}
func (m *MissedBlockBitmapEntry) XXX_Size() int {
	return m.Size()
}
func (m *MissedBlockBitmapEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_MissedBlockBitmapEntry.DiscardUnknown(m)
}

var xxx_messageInfo_MissedBlockBitmapEntry proto.InternalMessageInfo

func (m *MissedBlockBitmapEntry) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *MissedBlockBitmapEntry) GetBitmap() []byte {
	if m != nil {
		return m.Bitmap
	}
	return nil
}

// FirstTrackedHeightEntry is the first height at which a validator was
// observed within the downtime window currently in progress.
type FirstTrackedHeightEntry struct {
	Addr   []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Height int64  `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (m *FirstTrackedHeightEntry) Reset()         { *m = FirstTrackedHeightEntry{} }
func (m *FirstTrackedHeightEntry) String() string { return proto.CompactTextString(m) }
func (*FirstTrackedHeightEntry) ProtoMessage()    {}
func (*FirstTrackedHeightEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc650057d919c311, []int{2}
}
func (m *FirstTrackedHeightEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FirstTrackedHeightEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FirstTrackedHeightEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FirstTrackedHeightEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FirstTrackedHeightEntry.Merge(m, src)
}
func (m *FirstTrackedHeightEntry) XXX_Size() int {
	return m.Size()
}
func (m *FirstTrackedHeightEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FirstTrackedHeightEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FirstTrackedHeightEntry proto.InternalMessageInfo

func (m *FirstTrackedHeightEntry) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *FirstTrackedHeightEntry) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

// PendingEvidencePacketEntry is a single validator's queued downtime evidence
// packet: the validator's consensus address (the store key) and the
// JSON-encoded EvidencePacketData exactly as held by the consumer keeper's
// PendingEvidencePackets collection.
type PendingEvidencePacketEntry struct {
	Addr   []byte `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Packet []byte `protobuf:"bytes,2,opt,name=packet,proto3" json:"packet,omitempty"`
}

func (m *PendingEvidencePacketEntry) Reset()         { *m = PendingEvidencePacketEntry{} }
func (m *PendingEvidencePacketEntry) String() string { return proto.CompactTextString(m) }
func (*PendingEvidencePacketEntry) ProtoMessage()    {}
func (*PendingEvidencePacketEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_cc650057d919c311, []int{3}
}
func (m *PendingEvidencePacketEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PendingEvidencePacketEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PendingEvidencePacketEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PendingEvidencePacketEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PendingEvidencePacketEntry.Merge(m, src)
}
func (m *PendingEvidencePacketEntry) XXX_Size() int {
	return m.Size()
}
func (m *PendingEvidencePacketEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_PendingEvidencePacketEntry.DiscardUnknown(m)
}

var xxx_messageInfo_PendingEvidencePacketEntry proto.InternalMessageInfo

func (m *PendingEvidencePacketEntry) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func (m *PendingEvidencePacketEntry) GetPacket() []byte {
	if m != nil {
		return m.Packet
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "vaas.consumer.v1.GenesisState")
	proto.RegisterType((*MissedBlockBitmapEntry)(nil), "vaas.consumer.v1.MissedBlockBitmapEntry")
	proto.RegisterType((*FirstTrackedHeightEntry)(nil), "vaas.consumer.v1.FirstTrackedHeightEntry")
	proto.RegisterType((*PendingEvidencePacketEntry)(nil), "vaas.consumer.v1.PendingEvidencePacketEntry")
}

func init() { proto.RegisterFile("vaas/consumer/v1/genesis.proto", fileDescriptor_cc650057d919c311) }

var fileDescriptor_cc650057d919c311 = []byte{
	// 715 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0x5d, 0x4f, 0xdb, 0x3a,
	0x18, 0x6e, 0x0e, 0x3d, 0xa5, 0x98, 0x9e, 0x03, 0xc7, 0x07, 0x4a, 0x54, 0xb4, 0x52, 0xf5, 0xaa,
	0x9b, 0x50, 0xa2, 0x32, 0x4d, 0x5c, 0x53, 0x60, 0xa3, 0x17, 0x48, 0x55, 0x60, 0x5c, 0xec, 0xc6,
	0x73, 0x62, 0x37, 0xb5, 0x48, 0x9c, 0x28, 0x76, 0xd3, 0xf1, 0x2f, 0xf8, 0x53, 0x93, 0xb8, 0xe4,
	0x72, 0x57, 0xdb, 0x04, 0x7f, 0x64, 0xb2, 0xe3, 0x94, 0xcf, 0xde, 0xf9, 0xf5, 0xf3, 0xbc, 0xdf,
	0x8f, 0x0d, 0xda, 0x39, 0xc6, 0xc2, 0x0d, 0x12, 0x2e, 0xa6, 0x31, 0xcd, 0xdc, 0xbc, 0xef, 0x86,
	0x94, 0x53, 0xc1, 0x84, 0x93, 0x66, 0x89, 0x4c, 0xe0, 0xba, 0xc2, 0x9d, 0x12, 0x77, 0xf2, 0x7e,
	0xeb, 0x8d, 0xf6, 0xc8, 0xfb, 0xae, 0x98, 0xe0, 0x8c, 0x12, 0x34, 0xc7, 0xb4, 0x43, 0xcb, 0x65,
	0x7e, 0xe0, 0x46, 0x2c, 0x9c, 0xc8, 0x20, 0x62, 0x94, 0x4b, 0xe1, 0x4a, 0xca, 0x09, 0xcd, 0x62,
	0xc6, 0xa5, 0xf2, 0x7a, 0xb0, 0x8c, 0xc3, 0x46, 0x98, 0x84, 0x89, 0x3e, 0xba, 0xea, 0x64, 0x6e,
	0x61, 0x99, 0x65, 0xc6, 0x32, 0x6a, 0xee, 0x76, 0xc2, 0x24, 0x09, 0x23, 0xea, 0x6a, 0xcb, 0x9f,
	0x8e, 0x5d, 0xc9, 0x62, 0x2a, 0x24, 0x8e, 0x53, 0x43, 0xd8, 0x7e, 0x94, 0x0a, 0xfb, 0x01, 0x73,
	0xe5, 0x55, 0x4a, 0x4d, 0x27, 0xdd, 0xef, 0x35, 0xd0, 0xf8, 0x54, 0xf4, 0x76, 0x26, 0xb1, 0xa4,
	0xf0, 0x03, 0xa8, 0xa5, 0x38, 0xc3, 0xb1, 0xb0, 0xad, 0x8e, 0xd5, 0x5b, 0xdd, 0xdb, 0x72, 0x74,
	0xaf, 0x79, 0xdf, 0x39, 0x34, 0x2d, 0x8d, 0x34, 0x3c, 0xa8, 0xde, 0xfc, 0xdc, 0xa9, 0x78, 0x86,
	0x0c, 0x77, 0x01, 0x4c, 0xb3, 0x24, 0x67, 0x84, 0x66, 0xa8, 0x68, 0x11, 0x31, 0x62, 0xff, 0xd5,
	0xb1, 0x7a, 0x2b, 0xde, 0x7a, 0x89, 0x1c, 0x6a, 0x60, 0x48, 0xe0, 0x36, 0x58, 0xe1, 0x74, 0x86,
	0x82, 0x09, 0x66, 0xdc, 0x5e, 0xea, 0x58, 0xbd, 0xba, 0x57, 0xe7, 0x74, 0x76, 0xa8, 0x6c, 0x68,
	0x83, 0xe5, 0x34, 0xa3, 0x17, 0x07, 0x07, 0x67, 0x76, 0x55, 0x43, 0xa5, 0x09, 0xf7, 0x41, 0xbd,
	0x0c, 0x65, 0xff, 0xad, 0xab, 0xdb, 0x9c, 0x57, 0x37, 0x32, 0xc0, 0x90, 0x8f, 0x13, 0x53, 0xdb,
	0x9c, 0x0c, 0x4f, 0x01, 0x8c, 0xb0, 0x90, 0x28, 0x17, 0x01, 0xca, 0x68, 0x90, 0x23, 0x35, 0x23,
	0xbb, 0xa6, 0x43, 0xb4, 0x9c, 0x62, 0x80, 0x4e, 0x39, 0x40, 0xe7, 0xbc, 0x1c, 0xe0, 0xa0, 0x7a,
	0xfd, 0x6b, 0xc7, 0xf2, 0xd6, 0x94, 0xef, 0x85, 0x08, 0x3c, 0x1a, 0xe4, 0x0a, 0x83, 0x5f, 0xc1,
	0x46, 0xcc, 0x84, 0xa0, 0x04, 0xf9, 0x51, 0x12, 0x5c, 0x22, 0x9f, 0xc9, 0x18, 0xa7, 0xc2, 0x5e,
	0xee, 0x2c, 0xf5, 0x56, 0xf7, 0x7a, 0xce, 0x73, 0x75, 0x38, 0xa7, 0x9a, 0x3d, 0x50, 0xe4, 0x81,
	0xe6, 0x1e, 0x73, 0x99, 0x5d, 0x99, 0x32, 0x61, 0xfc, 0x1c, 0x15, 0x30, 0x00, 0x9b, 0x63, 0x96,
	0x09, 0x89, 0x64, 0x86, 0x83, 0x4b, 0x4a, 0xd0, 0x84, 0x2a, 0xf1, 0x08, 0xbb, 0xae, 0x53, 0xbc,
	0x7d, 0x99, 0xe2, 0xa3, 0xa2, 0x9f, 0x17, 0xec, 0x13, 0x4d, 0x7e, 0x9c, 0xe3, 0xff, 0xf1, 0x0b,
	0x58, 0xc0, 0x53, 0xd0, 0x14, 0x12, 0x87, 0x94, 0x20, 0x92, 0xcc, 0xb8, 0x1a, 0x09, 0x32, 0xab,
	0x5f, 0x79, 0xb6, 0xfa, 0x23, 0x83, 0x17, 0xab, 0xf7, 0x36, 0x0a, 0xb7, 0xa7, 0xb7, 0xf0, 0x1d,
	0xf8, 0xef, 0x41, 0x02, 0x6a, 0x93, 0x4a, 0x01, 0x40, 0x2b, 0x60, 0x6d, 0xae, 0x00, 0x75, 0x3f,
	0x24, 0x30, 0x02, 0x76, 0x4a, 0x39, 0x61, 0x3c, 0x44, 0x54, 0x01, 0x3c, 0x50, 0xb9, 0x83, 0x4b,
	0x2a, 0x85, 0xbd, 0xaa, 0x5b, 0xdc, 0x7d, 0xd9, 0xe2, 0xa8, 0xf0, 0x38, 0x36, 0x0e, 0x23, 0xcd,
	0x7f, 0xdc, 0x65, 0x33, 0x7d, 0x8d, 0x21, 0xe0, 0x3e, 0xb0, 0x27, 0x2c, 0x9c, 0x50, 0xa5, 0x00,
	0x1c, 0x09, 0x2a, 0xd1, 0x34, 0x25, 0x58, 0x52, 0x55, 0x60, 0xa3, 0x63, 0xf5, 0xaa, 0xde, 0xa6,
	0xc1, 0x2f, 0x34, 0xfc, 0x59, 0xa3, 0x43, 0x02, 0x7b, 0x60, 0xbd, 0x2c, 0x00, 0x31, 0x8e, 0x08,
	0xf5, 0xa5, 0xfd, 0x8f, 0xd6, 0xe4, 0xbf, 0xe5, 0xfd, 0x90, 0x1f, 0x51, 0x5f, 0x76, 0x8f, 0x40,
	0xf3, 0xf5, 0x25, 0x43, 0x08, 0xaa, 0x98, 0x90, 0x4c, 0x3f, 0xa7, 0x86, 0xa7, 0xcf, 0xb0, 0x09,
	0x6a, 0x85, 0x66, 0xf4, 0x0b, 0x69, 0x78, 0xc6, 0xea, 0x1e, 0x83, 0xad, 0x05, 0x7b, 0x5c, 0x14,
	0xa6, 0xd0, 0x85, 0x0e, 0xb3, 0xe4, 0x19, 0xab, 0x7b, 0x02, 0x5a, 0x8b, 0x67, 0xb5, 0x28, 0x52,
	0x31, 0xfe, 0xb2, 0xa0, 0xc2, 0x1a, 0x0c, 0x6f, 0xee, 0xda, 0xd6, 0xed, 0x5d, 0xdb, 0xfa, 0x7d,
	0xd7, 0xb6, 0xae, 0xef, 0xdb, 0x95, 0xdb, 0xfb, 0x76, 0xe5, 0xc7, 0x7d, 0xbb, 0xf2, 0xc5, 0x0d,
	0x99, 0x9c, 0x4c, 0x7d, 0x27, 0x48, 0x62, 0x17, 0x47, 0x11, 0xe3, 0x3e, 0x93, 0xc2, 0xd5, 0xff,
	0xd3, 0x37, 0xf7, 0xe9, 0xf7, 0xa9, 0xff, 0x1b, 0xbf, 0xa6, 0xdf, 0xd7, 0xfb, 0x3f, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x97, 0x93, 0xa9, 0x6a, 0x5c, 0x05, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ConsumerInDebt {
		i--
		if m.ConsumerInDebt {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x68
	}
	if m.HighestValsetUpdateId != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.HighestValsetUpdateId))
		i--
		dAtA[i] = 0x60
	}
	if len(m.PendingEvidencePackets) > 0 {
		for iNdEx := len(m.PendingEvidencePackets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PendingEvidencePackets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.ProviderChainId) > 0 {
		i -= len(m.ProviderChainId)
		copy(dAtA[i:], m.ProviderChainId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ProviderChainId)))
		i--
		dAtA[i] = 0x52
	}
	if m.StagedDowntimeParams != nil {
		{
			size, err := m.StagedDowntimeParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGenesis(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if len(m.FirstTrackedHeights) > 0 {
		for iNdEx := len(m.FirstTrackedHeights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FirstTrackedHeights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.MissedBlockBitmaps) > 0 {
		for iNdEx := len(m.MissedBlockBitmaps) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MissedBlockBitmaps[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if m.LastVscRecvTime != nil {
		n2, err2 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(*m.LastVscRecvTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastVscRecvTime):])
		if err2 != nil {
			return 0, err2
		}
		i -= n2
		i = encodeVarintGenesis(dAtA, i, uint64(n2))
		i--
		dAtA[i] = 0x32
	}
	{
		size, err := m.Provider.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if m.PreVAAS {
		i--
		if m.PreVAAS {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.NewChain {
		i--
		if m.NewChain {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.ProviderClientId) > 0 {
		i -= len(m.ProviderClientId)
		copy(dAtA[i:], m.ProviderClientId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ProviderClientId)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *MissedBlockBitmapEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MissedBlockBitmapEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MissedBlockBitmapEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Bitmap) > 0 {
		i -= len(m.Bitmap)
		copy(dAtA[i:], m.Bitmap)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Bitmap)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FirstTrackedHeightEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FirstTrackedHeightEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FirstTrackedHeightEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Height != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PendingEvidencePacketEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PendingEvidencePacketEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PendingEvidencePacketEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Packet) > 0 {
		i -= len(m.Packet)
		copy(dAtA[i:], m.Packet)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Packet)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Addr) > 0 {
		i -= len(m.Addr)
		copy(dAtA[i:], m.Addr)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Addr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = len(m.ProviderClientId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.NewChain {
		n += 2
	}
	if m.PreVAAS {
		n += 2
	}
	l = m.Provider.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.LastVscRecvTime != nil {
		l = github_com_cosmos_gogoproto_types.SizeOfStdTime(*m.LastVscRecvTime)
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.MissedBlockBitmaps) > 0 {
		for _, e := range m.MissedBlockBitmaps {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.FirstTrackedHeights) > 0 {
		for _, e := range m.FirstTrackedHeights {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.StagedDowntimeParams != nil {
		l = m.StagedDowntimeParams.Size()
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ProviderChainId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if len(m.PendingEvidencePackets) > 0 {
		for _, e := range m.PendingEvidencePackets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.HighestValsetUpdateId != 0 {
		n += 1 + sovGenesis(uint64(m.HighestValsetUpdateId))
	}
	if m.ConsumerInDebt {
		n += 2
	}
	return n
}

func (m *MissedBlockBitmapEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Bitmap)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *FirstTrackedHeightEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Height != 0 {
		n += 1 + sovGenesis(uint64(m.Height))
	}
	return n
}

func (m *PendingEvidencePacketEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Addr)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Packet)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewChain", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NewChain = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreVAAS", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PreVAAS = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Provider.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastVscRecvTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LastVscRecvTime == nil {
				m.LastVscRecvTime = new(time.Time)
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(m.LastVscRecvTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MissedBlockBitmaps", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MissedBlockBitmaps = append(m.MissedBlockBitmaps, MissedBlockBitmapEntry{})
			if err := m.MissedBlockBitmaps[len(m.MissedBlockBitmaps)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FirstTrackedHeights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FirstTrackedHeights = append(m.FirstTrackedHeights, FirstTrackedHeightEntry{})
			if err := m.FirstTrackedHeights[len(m.FirstTrackedHeights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StagedDowntimeParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.StagedDowntimeParams == nil {
				m.StagedDowntimeParams = &types.DowntimeParams{}
			}
			if err := m.StagedDowntimeParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProviderChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProviderChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PendingEvidencePackets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PendingEvidencePackets = append(m.PendingEvidencePackets, PendingEvidencePacketEntry{})
			if err := m.PendingEvidencePackets[len(m.PendingEvidencePackets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HighestValsetUpdateId", wireType)
			}
			m.HighestValsetUpdateId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HighestValsetUpdateId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerInDebt", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ConsumerInDebt = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MissedBlockBitmapEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MissedBlockBitmapEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MissedBlockBitmapEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = append(m.Addr[:0], dAtA[iNdEx:postIndex]...)
			if m.Addr == nil {
				m.Addr = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bitmap", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bitmap = append(m.Bitmap[:0], dAtA[iNdEx:postIndex]...)
			if m.Bitmap == nil {
				m.Bitmap = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FirstTrackedHeightEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FirstTrackedHeightEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FirstTrackedHeightEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = append(m.Addr[:0], dAtA[iNdEx:postIndex]...)
			if m.Addr == nil {
				m.Addr = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PendingEvidencePacketEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PendingEvidencePacketEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PendingEvidencePacketEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addr", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addr = append(m.Addr[:0], dAtA[iNdEx:postIndex]...)
			if m.Addr == nil {
				m.Addr = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Packet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Packet = append(m.Packet[:0], dAtA[iNdEx:postIndex]...)
			if m.Packet == nil {
				m.Packet = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
