// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vaas/v1/shared_consumer.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	types "github.com/cometbft/cometbft/abci/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	_07_tendermint "github.com/cosmos/ibc-go/v10/modules/light-clients/07-tendermint"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ConsumerParams defines the parameters for VAAS consumer module.
//
// Note this type is referenced in both the consumer and provider VAAS modules,
// and persisted on the provider, see MakeConsumerGenesis and
// SetConsumerGenesis.
type ConsumerParams struct {
	// TODO: Remove enabled flag and find a better way to setup integration tests
	// See: https://github.com/cosmos/interchain-security/issues/339
	Enabled bool `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// Sent VAAS related IBC packets will timeout after this duration
	VaasTimeoutPeriod time.Duration `protobuf:"bytes,2,opt,name=vaas_timeout_period,json=vaasTimeoutPeriod,proto3,stdduration" json:"vaas_timeout_period"`
	// The number of historical info entries to persist in store.
	// This param is a part of the cosmos sdk staking module. In the case of
	// a VAAS enabled consumer chain, the VAAS module acts as the staking module.
	HistoricalEntries int64 `protobuf:"varint,3,opt,name=historical_entries,json=historicalEntries,proto3" json:"historical_entries,omitempty"`
	// Unbonding period for the consumer,
	// which should be smaller than that of the provider in general.
	UnbondingPeriod time.Duration `protobuf:"bytes,4,opt,name=unbonding_period,json=unbondingPeriod,proto3,stdduration" json:"unbonding_period"`
	// How long the consumer may go without receiving a VSC packet before its
	// tx admission gate enters safe mode (only ibc.core and gov messages pass).
	SafeModeThreshold time.Duration `protobuf:"bytes,5,opt,name=safe_mode_threshold,json=safeModeThreshold,proto3,stdduration" json:"safe_mode_threshold"`
	// Provider-owned downtime detection window size, in consumer blocks.
	// Written by the provider into the consumer genesis and updated via
	// VSC packets; not locally updatable.
	SignedBlocksWindow int64 `protobuf:"varint,6,opt,name=signed_blocks_window,json=signedBlocksWindow,proto3" json:"signed_blocks_window,omitempty"`
	// Provider-owned minimum signing fraction per window.
	MinSignedPerWindow cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=min_signed_per_window,json=minSignedPerWindow,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_signed_per_window"`
}

func (m *ConsumerParams) Reset()         { *m = ConsumerParams{} }
func (m *ConsumerParams) String() string { return proto.CompactTextString(m) }
func (*ConsumerParams) ProtoMessage()    {}
func (*ConsumerParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a750255ca5daa3, []int{0}
}
func (m *ConsumerParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumerParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumerParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumerParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerParams.Merge(m, src)
}
func (m *ConsumerParams) XXX_Size() int {
	return m.Size()
}
func (m *ConsumerParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerParams.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerParams proto.InternalMessageInfo

func (m *ConsumerParams) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ConsumerParams) GetVaasTimeoutPeriod() time.Duration {
	if m != nil {
		return m.VaasTimeoutPeriod
	}
	return 0
}

func (m *ConsumerParams) GetHistoricalEntries() int64 {
	if m != nil {
		return m.HistoricalEntries
	}
	return 0
}

func (m *ConsumerParams) GetUnbondingPeriod() time.Duration {
	if m != nil {
		return m.UnbondingPeriod
	}
	return 0
}

func (m *ConsumerParams) GetSafeModeThreshold() time.Duration {
	if m != nil {
		return m.SafeModeThreshold
	}
	return 0
}

func (m *ConsumerParams) GetSignedBlocksWindow() int64 {
	if m != nil {
		return m.SignedBlocksWindow
	}
	return 0
}

// ConsumerGenesisState defines shared genesis information between provider and
// consumer
type ConsumerGenesisState struct {
	Params   ConsumerParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	Provider ProviderInfo   `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider"`
	// True for new chain, false for chain restart.
	// This is needed and always set to true; otherwise, new_chain in the consumer
	// genesis state will default to false
	NewChain bool `protobuf:"varint,3,opt,name=new_chain,json=newChain,proto3" json:"new_chain,omitempty"`
	// Flag indicating whether the consumer VAAS module starts in pre-VAAS state
	PreVAAS bool `protobuf:"varint,4,opt,name=preVAAS,proto3" json:"preVAAS,omitempty"`
}

func (m *ConsumerGenesisState) Reset()         { *m = ConsumerGenesisState{} }
func (m *ConsumerGenesisState) String() string { return proto.CompactTextString(m) }
func (*ConsumerGenesisState) ProtoMessage()    {}
func (*ConsumerGenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a750255ca5daa3, []int{1}
}
func (m *ConsumerGenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsumerGenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsumerGenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsumerGenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumerGenesisState.Merge(m, src)
}
func (m *ConsumerGenesisState) XXX_Size() int {
	return m.Size()
}
func (m *ConsumerGenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumerGenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumerGenesisState proto.InternalMessageInfo

func (m *ConsumerGenesisState) GetParams() ConsumerParams {
	if m != nil {
		return m.Params
	}
	return ConsumerParams{}
}

func (m *ConsumerGenesisState) GetProvider() ProviderInfo {
	if m != nil {
		return m.Provider
	}
	return ProviderInfo{}
}

func (m *ConsumerGenesisState) GetNewChain() bool {
	if m != nil {
		return m.NewChain
	}
	return false
}

func (m *ConsumerGenesisState) GetPreVAAS() bool {
	if m != nil {
		return m.PreVAAS
	}
	return false
}

// ProviderInfo defines all information a consumer needs from a provider
// Shared data type between provider and consumer
type ProviderInfo struct {
	// The client state for the provider client filled in on new chain, nil on restart.
	ClientState *_07_tendermint.ClientState `protobuf:"bytes,1,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"`
	// The consensus state for the provider client filled in on new chain, nil on restart.
	ConsensusState *_07_tendermint.ConsensusState `protobuf:"bytes,2,opt,name=consensus_state,json=consensusState,proto3" json:"consensus_state,omitempty"`
	// InitialValset filled in on new chain and on restart.
	InitialValSet []types.ValidatorUpdate `protobuf:"bytes,3,rep,name=initial_val_set,json=initialValSet,proto3" json:"initial_val_set"`
}

func (m *ProviderInfo) Reset()         { *m = ProviderInfo{} }
func (m *ProviderInfo) String() string { return proto.CompactTextString(m) }
func (*ProviderInfo) ProtoMessage()    {}
func (*ProviderInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_58a750255ca5daa3, []int{2}
}
func (m *ProviderInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProviderInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProviderInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProviderInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderInfo.Merge(m, src)
}
func (m *ProviderInfo) XXX_Size() int {
	return m.Size()
}
func (m *ProviderInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderInfo proto.InternalMessageInfo

func (m *ProviderInfo) GetClientState() *_07_tendermint.ClientState {
	if m != nil {
		return m.ClientState
	}
	return nil
}

func (m *ProviderInfo) GetConsensusState() *_07_tendermint.ConsensusState {
	if m != nil {
		return m.ConsensusState
	}
	return nil
}

func (m *ProviderInfo) GetInitialValSet() []types.ValidatorUpdate {
	if m != nil {
		return m.InitialValSet
	}
	return nil
}

func init() {
	proto.RegisterType((*ConsumerParams)(nil), "vaas.v1.ConsumerParams")
	proto.RegisterType((*ConsumerGenesisState)(nil), "vaas.v1.ConsumerGenesisState")
	proto.RegisterType((*ProviderInfo)(nil), "vaas.v1.ProviderInfo")
}

func init() { proto.RegisterFile("vaas/v1/shared_consumer.proto", fileDescriptor_58a750255ca5daa3) }

var fileDescriptor_58a750255ca5daa3 = []byte{
	// 697 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x41, 0x4f, 0xdb, 0x48,
	0x14, 0x8e, 0x09, 0x0b, 0x61, 0xc2, 0xc2, 0x32, 0x80, 0x36, 0x80, 0x36, 0x44, 0x1c, 0x56, 0x91,
	0x56, 0xd8, 0x1b, 0x56, 0xab, 0x5e, 0x4b, 0xa0, 0xaa, 0x2a, 0xb5, 0x28, 0x72, 0x28, 0x48, 0xbd,
	0x58, 0x63, 0xcf, 0xc3, 0x1e, 0x61, 0xcf, 0x58, 0x33, 0x93, 0xa4, 0xfc, 0x82, 0x5e, 0x7b, 0xec,
	0x0f, 0xe9, 0xb5, 0x77, 0x8e, 0xa8, 0xa7, 0xaa, 0x07, 0x5a, 0xc1, 0xb1, 0x7f, 0xa2, 0xf2, 0x78,
	0x0c, 0xe1, 0xd4, 0xf6, 0x14, 0x7f, 0xf3, 0xbd, 0xef, 0xcd, 0xf7, 0xf2, 0xde, 0x1b, 0xf4, 0xd7,
	0x98, 0x10, 0xe5, 0x8d, 0x7b, 0x9e, 0x4a, 0x88, 0x04, 0x1a, 0x44, 0x82, 0xab, 0x51, 0x06, 0xd2,
	0xcd, 0xa5, 0xd0, 0x02, 0xcf, 0x17, 0xb4, 0x3b, 0xee, 0x6d, 0x6e, 0x69, 0xe0, 0x14, 0x64, 0xc6,
	0xb8, 0xf6, 0x48, 0x18, 0x31, 0x4f, 0x5f, 0xe4, 0xa0, 0xca, 0xa8, 0x4d, 0x8f, 0x85, 0x91, 0x97,
	0xb2, 0x38, 0xd1, 0x51, 0xca, 0x80, 0x6b, 0xe5, 0x4d, 0x45, 0x8f, 0x7b, 0x53, 0xc8, 0x0a, 0xda,
	0xb1, 0x10, 0x71, 0x0a, 0x9e, 0x41, 0xe1, 0xe8, 0xcc, 0xa3, 0x23, 0x49, 0x34, 0x13, 0xdc, 0xf2,
	0x6b, 0xb1, 0x88, 0x85, 0xf9, 0xf4, 0x8a, 0x2f, 0x7b, 0xba, 0x11, 0x09, 0x95, 0x09, 0x15, 0x94,
	0x44, 0x09, 0x4a, 0x6a, 0xe7, 0x5b, 0x1d, 0x2d, 0x1d, 0x58, 0xeb, 0x03, 0x22, 0x49, 0xa6, 0x70,
	0x0b, 0xcd, 0x03, 0x27, 0x61, 0x0a, 0xb4, 0xe5, 0x74, 0x9c, 0x6e, 0xc3, 0xaf, 0x20, 0x1e, 0xa2,
	0xd5, 0xa2, 0xac, 0x40, 0xb3, 0x0c, 0xc4, 0x48, 0x07, 0x39, 0x48, 0x26, 0x68, 0x6b, 0xa6, 0xe3,
	0x74, 0x9b, 0x7b, 0x1b, 0x6e, 0xe9, 0xcd, 0xad, 0xbc, 0xb9, 0x87, 0xd6, 0x5b, 0xbf, 0x71, 0x79,
	0xbd, 0x5d, 0x7b, 0xf7, 0x65, 0xdb, 0xf1, 0x57, 0x0a, 0xfd, 0x71, 0x29, 0x1f, 0x18, 0x35, 0xde,
	0x45, 0x38, 0x61, 0x4a, 0x0b, 0xc9, 0x22, 0x92, 0x06, 0xc0, 0xb5, 0x64, 0xa0, 0x5a, 0xf5, 0x8e,
	0xd3, 0xad, 0xfb, 0x2b, 0xf7, 0xcc, 0x93, 0x92, 0xc0, 0x47, 0xe8, 0x8f, 0x11, 0x0f, 0x05, 0xa7,
	0x8c, 0xc7, 0x95, 0x81, 0xd9, 0x9f, 0x37, 0xb0, 0x7c, 0x27, 0xb6, 0xd7, 0x0f, 0xd1, 0xaa, 0x22,
	0x67, 0x10, 0x64, 0x82, 0x42, 0xa0, 0x13, 0x09, 0x2a, 0x11, 0x29, 0x6d, 0xfd, 0xf6, 0x0b, 0x35,
	0x15, 0xfa, 0x17, 0x82, 0xc2, 0x71, 0xa5, 0xc6, 0xff, 0xa2, 0x35, 0xc5, 0x62, 0x0e, 0x34, 0x08,
	0x53, 0x11, 0x9d, 0xab, 0x60, 0xc2, 0x38, 0x15, 0x93, 0xd6, 0x9c, 0xa9, 0x0a, 0x97, 0x5c, 0xdf,
	0x50, 0xa7, 0x86, 0xc1, 0x14, 0xad, 0x67, 0x8c, 0x07, 0x56, 0x95, 0x83, 0xac, 0x24, 0xf3, 0x1d,
	0xa7, 0xbb, 0xd0, 0xef, 0x15, 0xb7, 0x7d, 0xbe, 0xde, 0xde, 0x2a, 0x9b, 0xa7, 0xe8, 0xb9, 0xcb,
	0x84, 0x97, 0x11, 0x9d, 0xb8, 0xcf, 0x21, 0x26, 0xd1, 0xc5, 0x21, 0x44, 0x1f, 0xdf, 0xef, 0x22,
	0xdb, 0xdb, 0x43, 0x88, 0x7c, 0x9c, 0x31, 0x3e, 0x34, 0xe9, 0x06, 0x20, 0xcb, 0x5b, 0x76, 0x3e,
	0x38, 0x68, 0xad, 0xea, 0xf6, 0x53, 0xe0, 0xa0, 0x98, 0x1a, 0x6a, 0xa2, 0x01, 0xff, 0x8f, 0xe6,
	0x72, 0xd3, 0x7d, 0xd3, 0xf2, 0xe6, 0xde, 0x9f, 0xae, 0x9d, 0x5f, 0xf7, 0xe1, 0x70, 0xf4, 0x67,
	0x0b, 0x23, 0xbe, 0x0d, 0xc6, 0x8f, 0x50, 0x23, 0x97, 0x62, 0xcc, 0x28, 0x48, 0x3b, 0x05, 0xeb,
	0x77, 0xc2, 0x81, 0x25, 0x9e, 0xf1, 0x33, 0x61, 0x65, 0x77, 0xc1, 0x78, 0x0b, 0x2d, 0x70, 0x98,
	0x04, 0x51, 0x42, 0x18, 0x37, 0xbd, 0x6e, 0xf8, 0x0d, 0x0e, 0x93, 0x83, 0x02, 0x17, 0x03, 0x98,
	0x4b, 0x38, 0xd9, 0xdf, 0x1f, 0x9a, 0xce, 0x36, 0xfc, 0x0a, 0xee, 0xbc, 0x99, 0x41, 0x8b, 0xd3,
	0x79, 0xf1, 0x11, 0x5a, 0x2c, 0x37, 0x27, 0x50, 0x45, 0x1d, 0xd6, 0xfd, 0x3f, 0x2e, 0x0b, 0x23,
	0x77, 0x7a, 0xaf, 0xdc, 0xa9, 0x4d, 0x2a, 0x8a, 0x32, 0xa7, 0xa6, 0x74, 0xbf, 0x19, 0xdd, 0x03,
	0x7c, 0x8a, 0x96, 0x8b, 0x45, 0x06, 0xae, 0x46, 0xca, 0xa6, 0x2c, 0xeb, 0x72, 0x7f, 0x98, 0xb2,
	0x92, 0x95, 0x59, 0x97, 0xa2, 0x07, 0x18, 0x1f, 0xa1, 0x65, 0xc6, 0x99, 0x66, 0x24, 0x0d, 0xc6,
	0x24, 0x0d, 0x14, 0xe8, 0x56, 0xbd, 0x53, 0xef, 0x36, 0xf7, 0x3a, 0xd3, 0x79, 0x8a, 0x07, 0xc2,
	0x3d, 0x21, 0x29, 0xa3, 0x44, 0x0b, 0xf9, 0x32, 0xa7, 0x44, 0x83, 0xfd, 0xef, 0x7e, 0xb7, 0xf2,
	0x13, 0x92, 0x0e, 0x41, 0xf7, 0x1f, 0x5f, 0xde, 0xb4, 0x9d, 0xab, 0x9b, 0xb6, 0xf3, 0xf5, 0xa6,
	0xed, 0xbc, 0xbd, 0x6d, 0xd7, 0xae, 0x6e, 0xdb, 0xb5, 0x4f, 0xb7, 0xed, 0xda, 0xab, 0xbf, 0x63,
	0xa6, 0x93, 0x51, 0xe8, 0x46, 0x22, 0xf3, 0x48, 0x9a, 0x32, 0x1e, 0x32, 0xad, 0x3c, 0xf3, 0x5a,
	0xbd, 0x2e, 0x7f, 0xcc, 0x0b, 0x14, 0xce, 0x99, 0x99, 0xfe, 0xef, 0x7b, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7e, 0x5f, 0x54, 0x5e, 0xc9, 0x04, 0x00, 0x00,
}

func (m *ConsumerParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumerParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MinSignedPerWindow.Size()
		i -= size
		if _, err := m.MinSignedPerWindow.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintSharedConsumer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.SignedBlocksWindow != 0 {
		i = encodeVarintSharedConsumer(dAtA, i, uint64(m.SignedBlocksWindow))
		i--
		dAtA[i] = 0x30
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.SafeModeThreshold, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.SafeModeThreshold):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintSharedConsumer(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x2a
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.UnbondingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.UnbondingPeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintSharedConsumer(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x22
	if m.HistoricalEntries != 0 {
		i = encodeVarintSharedConsumer(dAtA, i, uint64(m.HistoricalEntries))
		i--
		dAtA[i] = 0x18
	}
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.VaasTimeoutPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VaasTimeoutPeriod):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintSharedConsumer(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x12
	if m.Enabled {
		i--
		if m.Enabled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ConsumerGenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsumerGenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsumerGenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PreVAAS {
		i--
		if m.PreVAAS {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.NewChain {
		i--
		if m.NewChain {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	{
		size, err := m.Provider.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSharedConsumer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintSharedConsumer(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *ProviderInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProviderInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProviderInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.InitialValSet) > 0 {
		for iNdEx := len(m.InitialValSet) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InitialValSet[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSharedConsumer(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.ConsensusState != nil {
		{
			size, err := m.ConsensusState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSharedConsumer(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ClientState != nil {
		{
			size, err := m.ClientState.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintSharedConsumer(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintSharedConsumer(dAtA []byte, offset int, v uint64) int {
	offset -= sovSharedConsumer(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ConsumerParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Enabled {
		n += 2
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.VaasTimeoutPeriod)
	n += 1 + l + sovSharedConsumer(uint64(l))
	if m.HistoricalEntries != 0 {
		n += 1 + sovSharedConsumer(uint64(m.HistoricalEntries))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.UnbondingPeriod)
	n += 1 + l + sovSharedConsumer(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.SafeModeThreshold)
	n += 1 + l + sovSharedConsumer(uint64(l))
	if m.SignedBlocksWindow != 0 {
		n += 1 + sovSharedConsumer(uint64(m.SignedBlocksWindow))
	}
	l = m.MinSignedPerWindow.Size()
	n += 1 + l + sovSharedConsumer(uint64(l))
	return n
}

func (m *ConsumerGenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovSharedConsumer(uint64(l))
	l = m.Provider.Size()
	n += 1 + l + sovSharedConsumer(uint64(l))
	if m.NewChain {
		n += 2
	}
	if m.PreVAAS {
		n += 2
	}
	return n
}

func (m *ProviderInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ClientState != nil {
		l = m.ClientState.Size()
		n += 1 + l + sovSharedConsumer(uint64(l))
	}
	if m.ConsensusState != nil {
		l = m.ConsensusState.Size()
		n += 1 + l + sovSharedConsumer(uint64(l))
	}
	if len(m.InitialValSet) > 0 {
		for _, e := range m.InitialValSet {
			l = e.Size()
			n += 1 + l + sovSharedConsumer(uint64(l))
		}
	}
	return n
}

func sovSharedConsumer(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSharedConsumer(x uint64) (n int) {
	return sovSharedConsumer(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ConsumerParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSharedConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumerParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumerParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Enabled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Enabled = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaasTimeoutPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.VaasTimeoutPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field HistoricalEntries", wireType)
			}
			m.HistoricalEntries = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.HistoricalEntries |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnbondingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.UnbondingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SafeModeThreshold", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.SafeModeThreshold, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedBlocksWindow", wireType)
			}
			m.SignedBlocksWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignedBlocksWindow |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSignedPerWindow", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinSignedPerWindow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSharedConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsumerGenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSharedConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsumerGenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsumerGenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Provider", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Provider.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NewChain", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.NewChain = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreVAAS", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.PreVAAS = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipSharedConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProviderInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSharedConsumer
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProviderInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProviderInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ClientState == nil {
				m.ClientState = &_07_tendermint.ClientState{}
			}
			if err := m.ClientState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsensusState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ConsensusState == nil {
				m.ConsensusState = &_07_tendermint.ConsensusState{}
			}
			if err := m.ConsensusState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialValSet", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialValSet = append(m.InitialValSet, types.ValidatorUpdate{})
			if err := m.InitialValSet[len(m.InitialValSet)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSharedConsumer(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSharedConsumer
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSharedConsumer(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSharedConsumer
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSharedConsumer
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSharedConsumer
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSharedConsumer
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSharedConsumer
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSharedConsumer        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSharedConsumer          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSharedConsumer = fmt.Errorf("proto: unexpected end of group")
)
