// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vaas/v1/wire.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	types "github.com/cometbft/cometbft/abci/types"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/x/staking/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// This packet is sent from provider chain to consumer chain if the validator
// set for consumer chain changes (due to new bonding/unbonding messages or
// slashing events).
type ValidatorSetChangePacketData struct {
	// validator_updates is the delta between the consumer's previous
	// validator set and the provider's current one for this epoch. May be
	// empty when the validator set did not change during the epoch; the
	// packet is still sent so consumer_in_debt stays in sync.
	ValidatorUpdates []types.ValidatorUpdate `protobuf:"bytes,1,rep,name=validator_updates,json=validatorUpdates,proto3" json:"validator_updates" yaml:"validator_updates"`
	// valset_update_id is the provider's monotonically increasing counter
	// identifying this update. The consumer uses it to detect and drop
	// out-of-order packets delivered over IBC v2's unordered channel.
	ValsetUpdateId uint64 `protobuf:"varint,2,opt,name=valset_update_id,json=valsetUpdateId,proto3" json:"valset_update_id,omitempty"`
	// consumer_in_debt signals whether the consumer chain has fallen behind
	// on its per-block fee payments to the provider. The provider stamps the
	// current value on every VSC packet so the consumer reconciles its local
	// debt flag each epoch. When true, the consumer's ante gate rejects
	// non-/ibc.core.* and non-/cosmos.gov.* messages until the provider
	// collects fees successfully and propagates false on the next VSC.
	ConsumerInDebt bool `protobuf:"varint,3,opt,name=consumer_in_debt,json=consumerInDebt,proto3" json:"consumer_in_debt,omitempty"`
	// is_snapshot indicates how the consumer must apply validator_updates.
	// false: validator_updates is a diff against the consumer's previous set
	// (the consumer accumulates). true: validator_updates is the provider's
	// complete current set (the consumer replaces its set with it). The
	// provider sends a snapshot while a consumer is behind on acks, so a
	// consumer that missed packets converges to the exact set in one packet.
	IsSnapshot bool `protobuf:"varint,4,opt,name=is_snapshot,json=isSnapshot,proto3" json:"is_snapshot,omitempty"`
	// downtime_params is the provider's current downtime detection params.
	// The consumer stages them on receipt (ordered by valset_update_id) and
	// activates them at its next window boundary.
	DowntimeParams *DowntimeParams `protobuf:"bytes,5,opt,name=downtime_params,json=downtimeParams,proto3" json:"downtime_params,omitempty"`
}

func (m *ValidatorSetChangePacketData) Reset()         { *m = ValidatorSetChangePacketData{} }
func (m *ValidatorSetChangePacketData) String() string { return proto.CompactTextString(m) }
func (*ValidatorSetChangePacketData) ProtoMessage()    {}
func (*ValidatorSetChangePacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a432f87dfb1130, []int{0}
}
func (m *ValidatorSetChangePacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorSetChangePacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorSetChangePacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorSetChangePacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorSetChangePacketData.Merge(m, src)
}
func (m *ValidatorSetChangePacketData) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorSetChangePacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorSetChangePacketData.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorSetChangePacketData proto.InternalMessageInfo

func (m *ValidatorSetChangePacketData) GetValidatorUpdates() []types.ValidatorUpdate {
	if m != nil {
		return m.ValidatorUpdates
	}
	return nil
}

func (m *ValidatorSetChangePacketData) GetValsetUpdateId() uint64 {
	if m != nil {
		return m.ValsetUpdateId
	}
	return 0
}

func (m *ValidatorSetChangePacketData) GetConsumerInDebt() bool {
	if m != nil {
		return m.ConsumerInDebt
	}
	return false
}

func (m *ValidatorSetChangePacketData) GetIsSnapshot() bool {
	if m != nil {
		return m.IsSnapshot
	}
	return false
}

func (m *ValidatorSetChangePacketData) GetDowntimeParams() *DowntimeParams {
	if m != nil {
		return m.DowntimeParams
	}
	return nil
}

// DowntimeParams carries the provider-owned downtime detection parameters.
// Stamped on every VSC packet so consumers converge on the provider's
// current values; also embedded in the consumer genesis at launch.
type DowntimeParams struct {
	// number of consumer blocks per tumbling detection window
	SignedBlocksWindow int64 `protobuf:"varint,1,opt,name=signed_blocks_window,json=signedBlocksWindow,proto3" json:"signed_blocks_window,omitempty"`
	// minimum fraction of the window a validator must sign
	MinSignedPerWindow cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=min_signed_per_window,json=minSignedPerWindow,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_signed_per_window"`
}

func (m *DowntimeParams) Reset()         { *m = DowntimeParams{} }
func (m *DowntimeParams) String() string { return proto.CompactTextString(m) }
func (*DowntimeParams) ProtoMessage()    {}
func (*DowntimeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_17a432f87dfb1130, []int{1}
}
func (m *DowntimeParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DowntimeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DowntimeParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DowntimeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DowntimeParams.Merge(m, src)
}
func (m *DowntimeParams) XXX_Size() int {
	return m.Size()
}
func (m *DowntimeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DowntimeParams.DiscardUnknown(m)
}

var xxx_messageInfo_DowntimeParams proto.InternalMessageInfo

func (m *DowntimeParams) GetSignedBlocksWindow() int64 {
	if m != nil {
		return m.SignedBlocksWindow
	}
	return 0
}

func init() {
	proto.RegisterType((*ValidatorSetChangePacketData)(nil), "vaas.v1.ValidatorSetChangePacketData")
	proto.RegisterType((*DowntimeParams)(nil), "vaas.v1.DowntimeParams")
}

func init() { proto.RegisterFile("vaas/v1/wire.proto", fileDescriptor_17a432f87dfb1130) }

var fileDescriptor_17a432f87dfb1130 = []byte{
	// 490 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x92, 0xcf, 0x8e, 0xd3, 0x30,
	0x10, 0xc6, 0x9b, 0xdd, 0xe5, 0x9f, 0x2b, 0x15, 0x88, 0x16, 0x11, 0x76, 0x51, 0x1a, 0x55, 0x08,
	0xe5, 0x42, 0x4c, 0x97, 0x1b, 0xa7, 0x55, 0xe9, 0x65, 0x25, 0x0e, 0x55, 0x2a, 0x40, 0xe2, 0x62,
	0x39, 0xf1, 0x28, 0xb5, 0x5a, 0xdb, 0x51, 0xec, 0xa6, 0xf4, 0x2d, 0x78, 0x0c, 0x1e, 0x80, 0x67,
	0x40, 0x7b, 0x5c, 0x71, 0x42, 0x1c, 0x2a, 0xd4, 0xbe, 0x01, 0x4f, 0x80, 0x62, 0xa7, 0xa0, 0x8a,
	0x93, 0x3d, 0xdf, 0xef, 0x9b, 0x19, 0x69, 0x66, 0x90, 0x5f, 0x53, 0xaa, 0x71, 0x3d, 0xc4, 0x2b,
	0x5e, 0x41, 0x52, 0x56, 0xca, 0x28, 0xff, 0x4e, 0xa3, 0x25, 0xf5, 0xf0, 0xec, 0x59, 0xae, 0xb4,
	0x50, 0x1a, 0x6b, 0x43, 0xe7, 0x5c, 0x16, 0xb8, 0x1e, 0x66, 0x60, 0xe8, 0x70, 0x1f, 0x3b, 0xfb,
	0xd9, 0x69, 0xa1, 0x0a, 0x65, 0xbf, 0xb8, 0xf9, 0xb5, 0xea, 0xb9, 0x01, 0xc9, 0xa0, 0x12, 0x5c,
	0x1a, 0x4c, 0xb3, 0x9c, 0x63, 0xb3, 0x2e, 0x41, 0xb7, 0xf0, 0x89, 0x2b, 0x4c, 0x5c, 0x96, 0x0b,
	0x1c, 0x1a, 0x7c, 0x3b, 0x42, 0x4f, 0xdf, 0xd3, 0x05, 0x67, 0xd4, 0xa8, 0x6a, 0x0a, 0xe6, 0xcd,
	0x8c, 0xca, 0x02, 0x26, 0x34, 0x9f, 0x83, 0x19, 0x53, 0x43, 0x7d, 0x85, 0x1e, 0xd6, 0x7b, 0x4e,
	0x96, 0x25, 0xa3, 0x06, 0x74, 0xe0, 0x45, 0xc7, 0x71, 0xf7, 0x22, 0x4a, 0xfe, 0x35, 0x4d, 0x9a,
	0xa6, 0xc9, 0xdf, 0x4a, 0xef, 0xac, 0x71, 0x14, 0x5d, 0x6f, 0xfa, 0x9d, 0xdf, 0x9b, 0x7e, 0xb0,
	0xa6, 0x62, 0xf1, 0x7a, 0xf0, 0x5f, 0xa1, 0x41, 0xfa, 0xa0, 0x3e, 0x4c, 0xd1, 0x7e, 0x8c, 0x1a,
	0x4d, 0x83, 0x69, 0x4d, 0x84, 0xb3, 0xe0, 0x28, 0xf2, 0xe2, 0x93, 0xb4, 0xe7, 0x74, 0x67, 0xbc,
	0x62, 0x8d, 0x33, 0x57, 0x52, 0x2f, 0x05, 0x54, 0x84, 0x4b, 0xc2, 0x20, 0x33, 0xc1, 0x71, 0xe4,
	0xc5, 0x77, 0xd3, 0xde, 0x5e, 0xbf, 0x92, 0x63, 0xc8, 0x8c, 0xdf, 0x47, 0x5d, 0xae, 0x89, 0x96,
	0xb4, 0xd4, 0x33, 0x65, 0x82, 0x13, 0x6b, 0x42, 0x5c, 0x4f, 0x5b, 0xc5, 0xbf, 0x44, 0xf7, 0x99,
	0x5a, 0x49, 0xc3, 0x05, 0x90, 0x92, 0x56, 0x54, 0xe8, 0xe0, 0x56, 0xe4, 0xc5, 0xdd, 0x8b, 0xc7,
	0x49, 0xbb, 0x9d, 0x64, 0xdc, 0xf2, 0x89, 0xc5, 0x69, 0x8f, 0x1d, 0xc4, 0x83, 0x2f, 0x1e, 0xea,
	0x1d, 0x5a, 0xfc, 0x97, 0xe8, 0x54, 0xf3, 0x42, 0x02, 0x23, 0xd9, 0x42, 0xe5, 0x73, 0x4d, 0x56,
	0x5c, 0x32, 0xb5, 0x0a, 0xbc, 0xc8, 0x8b, 0x8f, 0x53, 0xdf, 0xb1, 0x91, 0x45, 0x1f, 0x2c, 0xf1,
	0x19, 0x7a, 0x24, 0xb8, 0x24, 0x6d, 0x56, 0x09, 0xd5, 0x3e, 0xa5, 0x19, 0xc0, 0xbd, 0xd1, 0xb0,
	0x19, 0xe7, 0xcf, 0x4d, 0xff, 0xdc, 0xad, 0x50, 0xb3, 0x79, 0xc2, 0x15, 0x16, 0xd4, 0xcc, 0x92,
	0xb7, 0x50, 0xd0, 0x7c, 0x3d, 0x86, 0xfc, 0xfb, 0xd7, 0x17, 0xa8, 0xdd, 0xf0, 0x18, 0xf2, 0xd4,
	0x17, 0x5c, 0x4e, 0x6d, 0xb9, 0x09, 0x54, 0xae, 0xcb, 0xe8, 0xf2, 0x7a, 0x1b, 0x7a, 0x37, 0xdb,
	0xd0, 0xfb, 0xb5, 0x0d, 0xbd, 0xcf, 0xbb, 0xb0, 0x73, 0xb3, 0x0b, 0x3b, 0x3f, 0x76, 0x61, 0xe7,
	0xe3, 0xf3, 0x82, 0x9b, 0xd9, 0x32, 0x4b, 0x72, 0x25, 0x30, 0x5d, 0x2c, 0xb8, 0xcc, 0xb8, 0xd1,
	0xd8, 0xde, 0xec, 0x27, 0xf7, 0xd8, 0xb3, 0xca, 0x6e, 0xdb, 0xe3, 0x79, 0xf5, 0x27, 0x00, 0x00,
	0xff, 0xff, 0xf7, 0xe0, 0xcb, 0xf0, 0xcf, 0x02, 0x00, 0x00,
}

func (m *ValidatorSetChangePacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorSetChangePacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorSetChangePacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DowntimeParams != nil {
		{
			size, err := m.DowntimeParams.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintWire(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.IsSnapshot {
		i--
		if m.IsSnapshot {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.ConsumerInDebt {
		i--
		if m.ConsumerInDebt {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.ValsetUpdateId != 0 {
		i = encodeVarintWire(dAtA, i, uint64(m.ValsetUpdateId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.ValidatorUpdates) > 0 {
		for iNdEx := len(m.ValidatorUpdates) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorUpdates[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintWire(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *DowntimeParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DowntimeParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DowntimeParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.MinSignedPerWindow.Size()
		i -= size
		if _, err := m.MinSignedPerWindow.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintWire(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.SignedBlocksWindow != 0 {
		i = encodeVarintWire(dAtA, i, uint64(m.SignedBlocksWindow))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintWire(dAtA []byte, offset int, v uint64) int {
	offset -= sovWire(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ValidatorSetChangePacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.ValidatorUpdates) > 0 {
		for _, e := range m.ValidatorUpdates {
			l = e.Size()
			n += 1 + l + sovWire(uint64(l))
		}
	}
	if m.ValsetUpdateId != 0 {
		n += 1 + sovWire(uint64(m.ValsetUpdateId))
	}
	if m.ConsumerInDebt {
		n += 2
	}
	if m.IsSnapshot {
		n += 2
	}
	if m.DowntimeParams != nil {
		l = m.DowntimeParams.Size()
		n += 1 + l + sovWire(uint64(l))
	}
	return n
}

func (m *DowntimeParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SignedBlocksWindow != 0 {
		n += 1 + sovWire(uint64(m.SignedBlocksWindow))
	}
	l = m.MinSignedPerWindow.Size()
	n += 1 + l + sovWire(uint64(l))
	return n
}

func sovWire(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozWire(x uint64) (n int) {
	return sovWire(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ValidatorSetChangePacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWire
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorSetChangePacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorSetChangePacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorUpdates", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorUpdates = append(m.ValidatorUpdates, types.ValidatorUpdate{})
			if err := m.ValidatorUpdates[len(m.ValidatorUpdates)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValsetUpdateId", wireType)
			}
			m.ValsetUpdateId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ValsetUpdateId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsumerInDebt", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.ConsumerInDebt = bool(v != 0)
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsSnapshot", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsSnapshot = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DowntimeParams", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DowntimeParams == nil {
				m.DowntimeParams = &DowntimeParams{}
			}
			if err := m.DowntimeParams.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWire(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWire
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DowntimeParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowWire
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DowntimeParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DowntimeParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedBlocksWindow", wireType)
			}
			m.SignedBlocksWindow = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignedBlocksWindow |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinSignedPerWindow", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowWire
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthWire
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthWire
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinSignedPerWindow.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipWire(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthWire
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipWire(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowWire
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWire
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowWire
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthWire
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupWire
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthWire
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthWire        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowWire          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupWire = fmt.Errorf("proto: unexpected end of group")
)
